# Generated by Django 3.2.3 on 2021-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
    ]
