# Generated by Django 3.2.3 on 2021-05-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_head'),
        ('events', '0005_event_poc'),
    ]

    operations = [
    ]
