# Generated by Django 3.2.3 on 2021-05-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_merge_0005_event_head_0005_event_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poc',
        ),
    ]
