# Generated by Django 3.2.3 on 2021-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_poc'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='default1.jpg', upload_to='banners'),
        ),
    ]
