# Generated by Django 3.2.3 on 2021-05-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
    ]
